language: java
sudo: required
jdk:
  - oraclejdk9
install: true
script:
  - sudo apt-get update && sudo apt-get install oracle-java9-installer
  - sudo apt install oracle-java9-set-default
  - java -version
  - mvn clean install
